// src/services/api.ts
import axios from "axios";
import type { Post } from "@/types";

const API_URL = "https://jsonplaceholder.typicode.com/posts";

// Fetch all posts
export const fetchPosts = async (): Promise<Post[]> => {
  const response = await axios.get<Post[]>(API_URL);
  return response.data;
};

// Create a post (exclude id since it's generated by the API)
export const createPost = async (post: Omit<Post, "id">): Promise<Post> => {
  const response = await axios.post<Post>(API_URL, post);
  return response.data;
};

// Update a post (accept partial updates)
export const updatePost = async (
  id: number,
  updatedPost: Partial<Post>
): Promise<Post> => {
  const response = await axios.put<Post>(`${API_URL}/${id}`, updatedPost);
  return response.data;
};

// Delete a post (no return data expected)
export const deletePost = async (id: number): Promise<void> => {
  await axios.delete(`${API_URL}/${id}`);
};